# Generated by Django 4.1.7 on 2023-05-16 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_customer_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=300)),
                ('Author', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('PublishDate', models.DateField(default=datetime.date.today)),
                ('Status', models.BooleanField(default=False)),
                ('Price', models.IntegerField()),
                ('EntryPrice', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField()),
                ('BookId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.books')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20, unique=True)),
                ('Address', models.CharField(max_length=300)),
                ('DateOfBirth', models.DateField(default=datetime.date.today)),
                ('Password', models.CharField(max_length=20)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='cart',
            name='PersonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.persons'),
        ),
    ]
