# Generated by Django 4.1.7 on 2023-05-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_categories_remove_books_category_books_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='SellNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='Image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
